### ISSUE TITLE
Fossils not on tree when using sim.fossils.environment

### ISSUE THREAD

**Issue by TitouanCh** [fossilsim/fossilsim#2]
Sometimes, when using `sim.fossils.environment` _(environment-dependent model of preservation Holland, 1995)_ some fossils are not on the tree because they are aligned with the strata. 

**Steps to reproduce :**
- Execute the code below multiple times until you obtain "out of tree" fossils.
```
tree = ape::rtree(6)

max.age = tree.max(t)

strata = 7
wd = sim.gradient(strata)

f = sim.fossils.environment(t, max.age = max.age, strata = strata,
proxy.data = wd, PD = 0.5, DT = 1, PA = 1)
plot(f, t, show.proxy = TRUE, proxy.data = wd, strata = strata, show.strata = TRUE)
```
**Examples :**

![HollandBug1](https://user-images.githubusercontent.com/103992404/165483111-3186c4dd-e4c9-4646-8c75-997e1de1954f.png)
![holland-problemeGraphique](https://user-images.githubusercontent.com/103992404/165483384-800d3d74-1b3b-4af8-aa14-2ec970890c90.png)

**Tested :** Windows and Linux (RStudio + R 4.2.0)

**Comment by bjoelle** [comment]
we have a `use.exact.times` argument in `sim.fossils.intervals` to avoid this issue, but it seems it wasn't ported to `sim.fossils.environment` - I will add it
